### ISSUE TITLE
Construccion de la ventana1 primera parte

### ISSUE THREAD

**Issue by NocheSangrienta** [NocheSangrienta/Clase9#1]
Construir la ventana1 y hacer el formulario para ingresar la informacion del cliente

**Comment by OscuraRealidad** [comment]
Saludos, voy a encargarme de esta funcionalidad

**Comment by NocheSangrienta** [comment]
Listo Trabajo cumplido por favor revisar el nuevo issue para hacer en ventana1.py el formulario de registro del usuario
