### ISSUE TITLE
Construir en la ventana1 el formulario para ingresar el usuario 

### ISSUE THREAD

**Issue by NocheSangrienta** [NocheSangrienta/Clase9#4]
En este issue debes programar el boton de limpiar para limpiar todos los campos.
Tambien debes hacer el formulario para pedir los datos del usuario

**Comment by OscuraRealidad** [comment]
Voy a encargarme de este nuevo isuue #4

**Comment by NocheSangrienta** [comment]
ya se completo la tarea
