### ISSUE TITLE
Programar el boton para buscar el documento del usuario al cual se le va a buscar la contraseña

### ISSUE THREAD

**Issue by NocheSangrienta** [NocheSangrienta/Clase9#6]
Validar que se ingrese el documento del usuario al cual se le va a buscar la contraseña
Validar que el documento se un dato tipi numerico.
Crear la clase usuario con sus 11 propiedades
Solo considerar password
Buscar las preguntas para recuperar la contraseña

**Comment by OscuraRealidad** [comment]
Me voy a encargar de este issue, Voy a desarrollarlo
Pendiente de alguna sugerencia

**Comment by NocheSangrienta** [comment]
Listo Quedo pendiente de su primer push y pull request

**Comment by NocheSangrienta** [comment]
ya se completo la tarea
